/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package advancedswingtable;

import advancedswingtable.core.AdvancedTableColumn;
import advancedswingtable.model.PaginationModel;
import com.formdev.flatlaf.FlatLightLaf;
import advancedswingtable.pagination.PaginationController;
/**
 *
 * @author Pedro
 */
public class Demo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Demo.class.getName());
  PaginationController pagination;
     
    /**
     * Creates new form Demo
     */
    public Demo() {
        initComponents();
    testarTabela();

    }
 
private void testarTabela() {

    advancedTable1.configureColumns(
            new AdvancedTableColumn("Código", Long.class),
            new AdvancedTableColumn("Nome", String.class),
            new AdvancedTableColumn("Preço", Double.class),
            new AdvancedTableColumn("Ativo", Boolean.class)
    );

    for (int i = 1; i <= 100; i++) {

        advancedTable1.addRow(
                (long) i,
                "Produto " + i,
                i * 10.50,
                i % 2 == 0
        );
    }

    advancedTable1.setAdvStripedRows(true);
    advancedTable1.setAdvSortable(true);
    advancedTable1.setAdvResizableColumns(true);
    advancedTable1.setAdvReorderableColumns(true);

    pagination =
            new PaginationController(advancedTable1);

    pagination.refresh();

    paginationPanel2.setTable(advancedTable1);

    System.out.println("===== TESTE INICIAL =====");
    System.out.println(
            "Total de itens: "
            + pagination.getPagination().getTotalItems()
    );

    System.out.println(
            "Total de páginas: "
            + pagination.getPagination().getTotalPages()
    );

    System.out.println(
            "Página atual: "
            + pagination.getPagination().getCurrentPage()
    );

    System.out.println(
            "Linhas visíveis: "
            + advancedTable1.getRowCount()
    );

    System.out.println();
    System.out.println("===== INDO PARA PÁGINA 2 =====");

    pagination.goToPage(2);

    System.out.println(
            "Página atual: "
            + pagination.getPagination().getCurrentPage()
    );

    System.out.println(
            "Linhas visíveis: "
            + advancedTable1.getRowCount()
    );

    System.out.println();
    System.out.println("===== ADICIONANDO NOVA LINHA =====");

    advancedTable1.addRow(
            101L,
            "Produto 101",
            1060.50,
            true
    );

    pagination.refresh();

    System.out.println(
            "Total de itens após adicionar: "
            + pagination.getPagination().getTotalItems()
    );

    System.out.println(
            "Total de páginas após adicionar: "
            + pagination.getPagination().getTotalPages()
    );

    System.out.println(
            "Página atual: "
            + pagination.getPagination().getCurrentPage()
    );

    System.out.println(
            "Linhas visíveis: "
            + advancedTable1.getRowCount()
    );

    System.out.println();
    System.out.println("===== VOLTANDO PARA PÁGINA 1 =====");

    pagination.firstPage();

    System.out.println(
            "Página atual: "
            + pagination.getPagination().getCurrentPage()
    );

    System.out.println(
            "Linhas visíveis: "
            + advancedTable1.getRowCount()
    );

    System.out.println();
    System.out.println("===== TESTE FINALIZADO =====");
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFiltro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        advancedTable1 = new advancedswingtable.core.AdvancedTable();
        paginationPanel2 = new advancedswingtable.pagination.PaginationPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtFiltro.setText("jTextField1");
        txtFiltro.addActionListener(this::txtFiltroActionPerformed);
        txtFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltroKeyReleased(evt);
            }
        });

        advancedTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(advancedTable1);

        jButton1.setText("10");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("20");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("100");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(paginationPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3))))
                .addContainerGap(454, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(paginationPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFiltroActionPerformed
      
    }//GEN-LAST:event_txtFiltroActionPerformed

    private void txtFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroKeyReleased
    //   advancedTable1.setAdvFilter(txtFiltro.getText());
    }//GEN-LAST:event_txtFiltroKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      pagination.getPagination().setPageSize(10);
      pagination.refresh();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       pagination.getPagination().setPageSize(20);
       pagination.refresh();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       pagination.getPagination().setPageSize(100);
       pagination.refresh();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       FlatLightLaf.setup();
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Demo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private advancedswingtable.core.AdvancedTable advancedTable1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private advancedswingtable.pagination.PaginationPanel paginationPanel2;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables
}
